# Generated by Django 3.1.2 on 2020-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Profile_Pic',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
